# Generated by Django 4.1.7 on 2023-03-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caption',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
    ]
