# Generated by Django 4.1.7 on 2023-07-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Samuel\\PycharmProjects\\ActualBlogWebsite\\myblogsite\\media'),
        ),
    ]
