# Generated by Django 4.1.7 on 2023-08-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('callsign', models.CharField(max_length=5)),
                ('lat1', models.FloatField()),
                ('lat2', models.FloatField()),
                ('lat3', models.FloatField()),
                ('latNS', models.CharField(max_length=1)),
                ('long1', models.FloatField()),
                ('long2', models.FloatField()),
                ('long3', models.FloatField()),
                ('longNS', models.CharField(max_length=1)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('access', models.CharField(max_length=155)),
                ('open_date', models.DateField()),
                ('fsja', models.FloatField()),
                ('fs100', models.FloatField()),
                ('ssja', models.FloatField()),
                ('ss100', models.FloatField()),
                ('psja', models.FloatField()),
                ('ps100', models.FloatField()),
            ],
        ),
    ]
