# Generated by Django 4.1.7 on 2023-08-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='fs100',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='fsja',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='open_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ps100',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='psja',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ss100',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ssja',
            field=models.FloatField(default=None, null=True),
        ),
    ]
