# Generated by Django 4.1.7 on 2023-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_airport_fs100_alter_airport_fsja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='fs100',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='fsja',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ps100',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='psja',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ss100',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ssja',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
