# Generated by Django 4.1.7 on 2023-08-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_airport_fs100_alter_airport_fsja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='longNS',
            new_name='longEW',
        ),
    ]
