# Generated by Django 4.1.7 on 2023-08-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_rename_longns_airport_longew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='fs100',
            new_name='FS100',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='fsja',
            new_name='FSJA',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='ps100',
            new_name='PS100',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='psja',
            new_name='PSJA',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='ss100',
            new_name='SS100',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='ssja',
            new_name='SSJA',
        ),
    ]
