# Generated by Django 4.1.7 on 2023-08-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_rename_fs100_airport_fs100_rename_fsja_airport_fsja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='control_tower',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
