# Generated by Django 4.1.7 on 2023-08-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_airport_control_tower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='FS100',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='FSJA',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='PS100',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='PSJA',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='SS100',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='SSJA',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
